# Generated by Django 2.2.28 on 2022-10-29 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 10, 29, 19, 2, 0, 186929), verbose_name='Опубликована'),
        ),
    ]
